tasks:
  - name: Setup AWS CLI
    init: |
      # AWS CLI is already installed
      echo "AWS CLI version:"
      aws --version
    command: |
      echo "AWS Practice Environment Ready!"
      echo "Run 'aws configure' to set up your credentials"
      echo ""
      echo "Available commands:"
      echo "  aws configure - Configure AWS credentials"
      echo "  aws s3 ls - List S3 buckets"
      echo "  aws ec2 describe-instances - List EC2 instances"

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - redhat.vscode-yaml
