#!/usr/bin/env bash   
echo "== create bucket"

# Check if a variable is passed as an argument
if [ -z "$1" ]; then
  echo "Chill bro, theres no bucket name provided. eg: ./bucket my-bucket-name"
  exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket --bucket $BUCKET_NAME --region us-east-1 --query Location --output text